<?php
/**
 * Copyright 2018 MageStack. All rights reserved.
 * 
 */
?>
<div id="magestack-main-container">
    <h2 class="head">1 ) <?php echo __('Need custom development for MageStack modules, plugins?'); ?></h2>
    <div class="how">
        <h3><?php echo __('Projects Codeable experts work on every day include:'); ?></h3>
        <ul>
            <li><?php echo __('Creating MODULES from scratch – design to completion'); ?></li>
            <li><?php echo __('Creating WEBSITES from scratch – design to completion (including our modules)'); ?></li>
            <li><?php echo __('Customize any MODULES, THEMES following your requirement'); ?></li>
            <li><?php echo __('Magento INSTALLATION , DEMO CONTENT INSTALL , THEME INSTALLATION, MODULES INSTALLATION'); ?></li>
            <li><?php echo __('FULL SITE MIGRATION'); ?></li>
        </ul>
    </div>
    <div class="road-map">
        <h2 class="head">2 ) <?php echo __('The Custom Work roadmap.') ?></h2>
        <div class="map-content">
            <p><?php echo __('After you and we reach an agreement, we will let you know when we can start the Custom Work, and how much time we need to finish it. The minimum assistance time is 1 hour. '); ?></p>
            <p><?php echo __('We suggest grouping multiple small requests in one bigger order so that the job could cover at least one working hour.'); ?></p>
        </div>
    </div>
    <div class="how-connect">
        <h2 class="head">3 ) <?php echo __('Connect.') ?></h2>
        <ul>
            <li>1 ) <?php echo __('Github ( report issues ) -  '); ?><a href="https://github.com/MageStack">https://github.com/MageStack</a> </li>
            <li>2 ) <?php echo __('Send Request (Ex : Custom Job.....) - '); ?><a href="mailto:magestackpro@gmail.com?Subject=Hello">magestackpro@gmail.com</a></li>
            <li>3 ) <?php echo __('Freelancer Profile -'); ?><a href="https://www.freelancer.com/u/ngay">https://www.freelancer.com/u/ngay</a> </li>
        </ul>
    </div>
</div>
<style>
    .how-connect {margin-top: 25px}
    .how-connect ul {list-style: none}
    .how , .how ul, .how-connect ul {margin-left: 25px;}
    .how h3 {
        font-size: 18px;
        color: #1a1a1a;
    }
    .how ul li, .how-connect ul li {padding: 10px 0}
    .how {border-bottom: 1px solid #ccc;}
    .road-map {margin-top: 25px;}
    #magestack-main-container {
        border: 1px solid #ccc;
        padding: 10px;
    }
    h2.head {
        text-decoration: underline;
        color: #005999;
    }
    .map-content {margin-left: 25px;padding-bottom: 30px;border-bottom: 1px solid #ccc}
</style>
